# Prototypes
array([0.21486111, 0.51822529]); 1.0
array([0.3071172 , 0.90652702]); 1.0
array([0.11579366, 0.10513306]); 1.0
array([0.10640605, 0.25691731]); 1.0
array([0.11661097, 0.38743686]); 1.0
array([0.09120224, 0.76194532]); 1.0
array([0.07524046, 0.26963197]); 1.0
array([0.63434601, 0.33295285]); 2.0
array([0.52925187, 0.05883835]); 2.0
array([ 0.62446646, -0.00194885]); 2.0
array([0.43329317, 0.52703865]); 2.0
array([0.60416366, 0.5244503 ]); 2.0
array([0.42265847, 0.27232979]); 2.0
array([0.44177384, 0.64665253]); 2.0
array([0.73174454, 0.78521208]); 3.0
array([0.93678217, 0.61235258]); 3.0
array([0.79926015, 0.2059515 ]); 3.0
array([0.82357316, 0.46960299]); 3.0
array([0.84540253, 0.0284731 ]); 3.0
array([0.62451394, 0.33133901]); 3.0
array([0.89011044, 0.83273847]); 3.0

# T_d sequences
[array([0.36488784, 0.6244902 , 0.62942997, 0.68304527]), array([0.01326212, 0.04365572, 0.0819857 , 0.15554228, 0.23143441,       0.27098088, 0.3018344 , 0.33214593, 0.36019486, 0.42851993,       0.49391414, 0.5213378 , 0.56969561, 0.62950255, 0.70429893,       0.7735787 , 0.86963274])]

# Genetic sequences
[array([ True,  True,  True,  True]), array([ True, False,  True, False,  True, False,  True, False,  True,        True, False, False, False, False, False, False,  True])]

# Genetic purity
True

# Genetic algoritm's time
0.8894546031951904

# S_d sequences
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (0, 0, 0)
[array([ True, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (3, 2, 0.9090909090909091)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False,  True,       False, False, False, False, False, False, False, False])]; (3, 2, 0.9090909090909091)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,        True, False, False, False, False, False, False, False])]; (3, 2, 0.9090909090909091)
[array([False,  True, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (3, 2, 0.9090909090909091)
[array([False, False, False, False]), array([ True, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (3, 2, 0.9090909090909091)
[array([False, False, False, False]), array([False, False, False, False, False, False,  True, False, False,       False, False, False, False, False, False, False, False])]; (3, 2, 0.9090909090909091)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False,  True])]; (3, 2, 0.9090909090909091)
[array([False, False, False,  True]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (3, 2, 0.9090909090909091)
[array([False, False, False, False]), array([False, False, False, False,  True, False, False, False, False,       False, False, False, False, False, False, False, False])]; (3, 2, 0.9090909090909091)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False,  True, False, False, False, False, False, False])]; (3, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False,  True, False, False, False,       False, False, False, False, False, False, False, False])]; (3, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False,  True, False,       False, False, False, False, False, False, False, False])]; (3, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False,  True, False, False, False])]; (3, 2, 1.0)
[array([False, False, False, False]), array([False, False, False,  True, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (3, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False,  True, False, False, False, False])]; (3, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False,  True, False, False, False, False, False])]; (3, 2, 1.0)
[array([ True, False, False, False]), array([False, False, False, False, False, False,  True, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False, False, False,  True]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False,  True])]; (4, 2, 0.8181818181818181)
[array([False, False, False, False]), array([False, False, False, False,  True, False, False, False, False,       False, False, False, False, False, False, False,  True])]; (4, 2, 0.8181818181818181)
[array([ True, False, False, False]), array([False, False, False, False,  True, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False,  True, False, False]), array([False, False,  True, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False, False, False, False]), array([False, False, False, False,  True, False, False, False, False,        True, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False, False, False, False]), array([False, False, False, False,  True, False, False, False,  True,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([ True, False, False, False]), array([False, False,  True, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False,  True, False,  True]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False,  True, False, False]), array([ True, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False, False, False, False]), array([False, False, False, False,  True, False,  True, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,        True, False, False, False, False, False, False,  True])]; (4, 2, 0.8181818181818181)
[array([False,  True,  True, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([ True, False, False, False]), array([ True, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False, False, False,  True]), array([False, False,  True, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([ True, False, False,  True]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False,  True,       False, False, False, False, False, False, False,  True])]; (4, 2, 0.8181818181818181)
[array([False, False, False, False]), array([False, False, False, False, False, False,  True, False, False,       False, False, False, False, False, False, False,  True])]; (4, 2, 0.8181818181818181)
[array([False, False, False,  True]), array([ True, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([ True, False,  True, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False, False, False, False]), array([False, False, False, False, False, False,  True, False, False,        True, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([ True,  True, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False, False, False, False]), array([ True, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False,  True])]; (4, 2, 0.8181818181818181)
[array([False, False, False, False]), array([False, False, False, False, False, False,  True, False,  True,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([ True, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False,  True])]; (4, 2, 0.8181818181818181)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False,  True,        True, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False, False, False, False]), array([ True, False, False, False, False, False,  True, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False, False, False, False]), array([ True, False, False, False, False, False, False, False,  True,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False, False, False, False]), array([ True, False, False, False, False, False, False, False, False,        True, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False, False, False, False]), array([ True, False, False, False,  True, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False,  True, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False,  True])]; (4, 2, 0.8181818181818181)
[array([ True, False, False, False]), array([False, False, False, False, False, False, False, False, False,        True, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([ True, False, False, False]), array([False, False, False, False, False, False, False, False,  True,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([ True, False, False, False]), array([False, False, False, False, False, False, False,  True, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False,  True, False, False, False, False, False,  True])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False,  True,  True, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False,  True, False, False, False,  True])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False,  True, False, False, False, False,       False, False, False, False, False, False,  True, False])]; (4, 2, 0.9166666666666666)
[array([ True, False, False, False]), array([False, False, False, False, False,  True, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False,  True, False, False, False, False,       False, False, False, False,  True, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False,  True, False, False, False, False,       False, False, False, False, False,  True, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False,  True, False, False, False, False,       False, False,  True, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False,  True, False, False, False, False,       False, False, False,  True, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False,  True, False, False, False, False,       False,  True, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False,  True, False, False, False, False,  True])]; (4, 2, 0.9166666666666666)
[array([False,  True, False, False]), array([False,  True, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False,  True, False, False,  True, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False,  True,  True, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([ True, False, False, False]), array([False, False, False,  True, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False,  True]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False,  True, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False,  True]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False,  True, False, False])]; (4, 2, 0.9166666666666666)
[array([ True, False, False, False]), array([False,  True, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,        True, False, False, False, False,  True, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,        True, False, False, False,  True, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,        True, False, False,  True, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,        True, False,  True, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False,  True]), array([False,  True, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False,  True, False, False, False, False, False,       False, False, False, False, False, False, False,  True])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,        True,  True, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False,  True,       False, False, False, False, False, False,  True, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False,  True, False, False,       False, False, False, False, False,  True, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False,  True, False, False,       False, False, False, False,  True, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False,  True,       False, False, False, False, False,  True, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False,  True, False, False,       False, False, False,  True, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False,  True, False, False,       False, False,  True, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False,  True, False, False,       False,  True, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False,  True,       False, False, False, False,  True, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False,  True,       False, False, False,  True, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False,  True,  True, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False,  True,       False, False,  True, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False,  True,       False,  True, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([ True, False, False, False, False, False, False, False, False,       False, False, False, False,  True, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([ True, False, False, False, False, False, False, False, False,       False, False, False,  True, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([ True, False, False, False, False, False, False, False, False,       False, False,  True, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([ True, False, False, False, False, False, False, False, False,       False,  True, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([ True, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False,  True, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False,  True, False, False,  True])]; (4, 2, 0.9166666666666666)
[array([ True, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False,  True, False])]; (4, 2, 0.9166666666666666)
[array([ True, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False,  True, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([ True, False, False, False, False, False, False,  True, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([ True, False, False, False, False,  True, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,        True, False, False, False, False, False,  True, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False,  True, False, False, False, False, False,        True, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False,  True, False, False, False, False,  True,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([ True, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False,  True, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False,  True, False, False,  True, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([ True, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False,  True, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([ True, False, False,  True, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False,  True,  True, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False, False,  True, False,       False, False, False, False, False, False, False,  True])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([ True,  True, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False,  True, False, False,       False, False, False, False, False, False,  True, False])]; (4, 2, 0.9166666666666666)
[array([False,  True, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False,  True, False])]; (4, 2, 0.9166666666666666)
[array([ True, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False,  True, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False,  True, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False,  True, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False,  True, False, False, False,       False, False, False, False, False, False, False,  True])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False, False,  True, False,        True, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False, False, False,  True,  True,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False,  True, False, False,  True,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False,  True, False, False, False,        True, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False, False, False, False,  True, False,  True, False,       False, False, False, False, False, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False,  True, False, False, False,  True, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False,  True, False, False, False, False,  True, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False,  True, False,  True, False, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False,  True, False, False,  True, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False,  True,  True, False, False, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False,  True, False, False, False,  True, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False,  True, False,  True, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False,  True,  True, False, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False,  True, False, False,  True, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False,  True,  True, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False,  True, False, False, False, False, False,       False, False, False, False, False, False,  True, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False,  True, False, False, False, False, False,       False, False, False, False, False,  True, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False,  True, False, False, False, False, False,       False, False, False, False,  True, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False,  True, False, False, False, False, False,       False, False, False,  True, False, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False,  True, False, False, False, False, False,       False,  True, False, False, False, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False,  True, False, False, False, False, False,       False, False,  True, False, False, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False,  True, False, False, False,  True, False,       False, False, False, False, False, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False,  True, False,  True, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False,  True, False,       False, False, False, False, False, False,  True, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False,  True, False,       False, False, False, False, False,  True, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False,  True, False,       False, False, False, False,  True, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False,  True, False,       False, False, False,  True, False, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False,  True, False,       False, False,  True, False, False, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False,  True, False,       False,  True, False, False, False, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False,  True, False, False, False,       False, False, False, False, False,  True, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False,  True, False, False, False,       False, False, False, False, False, False,  True, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False,  True, False, False, False,       False, False, False,  True, False, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False,  True, False, False, False,       False, False, False, False,  True, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False,  True, False, False, False,       False,  True, False, False, False, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False,  True, False, False, False,       False, False,  True, False, False, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False,  True, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 3, 0.9090909090909091)
[array([False, False, False, False]), array([False, False,  True, False, False, False,  True, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False, False, False, False]), array([False, False,  True, False, False, False, False, False,  True,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False, False, False, False]), array([False, False,  True, False, False, False, False, False, False,        True, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False, False, False, False]), array([False, False,  True, False, False, False, False,  True, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False,  True, False, False, False, False, False, False,       False,  True, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False,  True, False, False, False, False, False, False,       False, False,  True, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False,  True, False, False, False, False, False, False,       False, False, False, False,  True, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False, False,  True, False, False, False, False, False, False,       False, False, False,  True, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False,  True, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 3, 0.9090909090909091)
[array([False, False,  True,  True]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.8181818181818181)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False,  True, False])]; (4, 3, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False,  True,  True])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False,  True, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 3, 1.0)
[array([False, False, False, False]), array([False,  True, False, False,  True, False, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False,  True, False, False, False, False,  True, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False,  True, False, False, False, False, False, False,  True,       False, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False,  True, False, False, False, False, False, False, False,        True, False, False, False, False, False, False, False])]; (4, 2, 0.9166666666666666)
[array([False, False, False, False]), array([False,  True, False, False, False,  True, False, False, False,       False, False, False, False, False, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False,  True, False, False, False, False, False, False, False,       False, False,  True, False, False, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False,  True, False, False, False, False, False, False, False,       False, False, False,  True, False, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False,  True, False, False, False, False, False, False, False,       False, False, False, False,  True, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False,  True, False, False, False, False, False,  True, False,       False, False, False, False, False, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False,  True, False, False, False, False, False, False, False,       False,  True, False, False, False, False, False, False])]; (4, 2, 1.0)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False,  True, False, False])]; (4, 3, 1.0)
[array([ True, False, False, False]), array([False, False, False, False,  True, False, False, False, False,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([False,  True, False, False]), array([ True, False,  True, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([False, False, False, False,  True, False,  True, False, False,        True, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([False, False, False, False,  True, False,  True, False,  True,       False, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([False,  True,  True, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([False,  True, False,  True]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([ True, False, False, False]), array([False, False, False, False, False, False,  True, False, False,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([False,  True, False,  True]), array([False, False,  True, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([False, False,  True,  True]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([ True, False, False, False]), array([False, False,  True, False, False, False, False, False, False,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([False,  True, False,  True]), array([ True, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([ True, False, False, False]), array([False, False, False, False, False, False, False, False,  True,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([False, False,  True,  True]), array([ True, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([False, False,  True,  True]), array([False, False,  True, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([ True, False, False, False]), array([False, False,  True, False, False, False,  True, False, False,       False, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([ True, False, False, False]), array([False, False,  True, False, False, False, False, False,  True,       False, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([ True, False, False, False]), array([False, False,  True, False, False, False, False, False, False,        True, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([ True, False, False, False]), array([False, False, False, False, False, False, False, False, False,        True, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([ True, False, False, False]), array([False, False, False, False, False, False, False, False,  True,        True, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([False, False,  True, False, False, False, False, False, False,        True, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([ True, False, False, False]), array([False, False,  True, False,  True, False, False, False, False,       False, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([ True, False, False, False,  True, False, False, False, False,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([False, False,  True, False, False, False, False, False,  True,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([False, False, False, False,  True, False, False, False,  True,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([False, False,  True, False, False, False,  True, False, False,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([False, False,  True, False, False, False, False, False,  True,        True, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([False, False,  True, False, False, False,  True, False,  True,       False, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([False, False,  True, False, False, False,  True, False, False,        True, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([False, False, False, False,  True, False,  True, False, False,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([ True, False, False, False,  True, False,  True, False, False,       False, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([ True, False, False, False,  True, False, False, False,  True,       False, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([ True, False, False, False,  True, False, False, False, False,        True, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([ True, False, False, False, False, False, False, False, False,        True, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([False, False, False, False,  True, False, False, False, False,        True, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([False, False, False, False,  True, False, False, False,  True,        True, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([ True, False, False, False, False, False, False, False,  True,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([False,  True, False, False]), array([False, False,  True, False, False, False, False, False, False,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([ True, False, False, False, False, False,  True, False, False,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([ True, False, False, False, False, False, False, False,  True,        True, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([False,  True, False, False]), array([ True, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([ True, False, False, False, False, False,  True, False,  True,       False, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([ True, False, False, False, False, False,  True, False, False,        True, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([False, False, False, False, False, False, False, False,  True,        True, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([ True, False, False, False]), array([ True, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([False, False, False, False, False, False,  True, False,  True,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([ True,  True, False, False]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([False, False, False, False, False, False,  True, False,  True,        True, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([False,  True, False, False]), array([False, False,  True, False,  True, False, False, False, False,       False, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([ True,  True, False, False]), array([False, False, False, False, False, False, False, False, False,        True, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([ True,  True, False, False]), array([False, False, False, False, False, False, False, False,  True,       False, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([ True, False, False,  True]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([ True,  True, False, False]), array([False, False, False, False, False, False,  True, False, False,       False, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([ True,  True, False, False]), array([False, False, False, False,  True, False, False, False, False,       False, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([ True,  True, False, False]), array([False, False,  True, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([ True,  True, False, False]), array([ True, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([False, False, False,  True]), array([False, False,  True, False, False, False, False, False, False,       False, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([False, False, False, False]), array([False, False, False, False, False, False,  True, False, False,        True, False, False, False, False, False, False,  True])]; (5, 2, 0.7272727272727273)
[array([ True,  True, False,  True]), array([False, False, False, False, False, False, False, False, False,       False, False, False, False, False, False, False, False])]; (5, 2, 0.7272727272727273)
[array([ True,  True, False,  True]), array([False, False, False, False, False, False, False,  True, False,       False, False, False, False, False, False, False, False])]; (5, 1, 0.75)

# M_d
[0.9367821692787773, 0.9065270171043334]

# m_d
[0.07524046165787432, -0.0019488503064283358]

# Time
1.7998909950256348

# Number of evaluated nodes
232
